"""Ship AI CORA — queries, reliability system, Resonance corruption."""

from __future__ import annotations
import random
from typing import Dict, Optional, Tuple


# ── CORA response library ────────────────────────────────────────────────────

CORA_RESPONSES: Dict[str, Dict[str, str]] = {
    "reactor": {
        "accurate": (
            "Current reactor output: 11.2% of design capacity. "
            "Primary limiting factor appears to be coolant loop pressure — "
            "currently reading 1.4 MPa against a nominal 3.0 MPa. "
            "I should note: my sensor array B-7 is currently offline, "
            "which may affect the accuracy of some readings."
        ),
        "corrupted": (
            "Current reactor output: 11.2% of design capacity. "
            "Primary limiting factor: magnetic confinement field at 94.2% "
            "— just below the 95% shutdown threshold. I recommend "
            "increasing confinement field power. Coolant loop nominal."
        ),
    },
    "ftl": {
        "accurate": (
            "FTL event occurred on Cycle -4,291. My logs for that period "
            "show some data corruption — I cannot verify all details. "
            "What I can confirm: the drive engaged, the transit completed, "
            "and the resulting position is inconsistent with the approved "
            "mission trajectory."
        ),
        "corrupted": (
            "FTL event occurred on Cycle -4,291. Drive performance was "
            "nominal. Transit completed successfully. Current position "
            "deviation is the result of an unforeseeable quantum-level "
            "interference event. No human error or intervention involved."
        ),
    },
    "factions": {
        "accurate": (
            "I monitor four faction groups: The Navigators (Captain Okonkwo, "
            "focused on propulsion and navigation), The Keepers (Dr. Tanaka, "
            "focused on cryosleeper preservation), The Listeners (Silas Venn, "
            "focused on Resonance study), and The Ghosts (loose alliance, "
            "survival-focused). Current inter-faction tension: elevated."
        ),
        "corrupted": (
            "I monitor three faction groups: The Navigators, The Keepers, "
            "and The Listeners. There are also some independent crew members. "
            "Inter-faction relations are stable."
        ),
    },
    "resonance": {
        "accurate": (
            "The Resonance is an extradimensional phenomenon detected "
            "throughout the intergalactic void. It appears to interact "
            "with certain ship systems and — I note this with uncertainty — "
            "with biological neural activity. I have logged 847 confirmed "
            "anomalous events that correlate with Resonance proximity. "
            "I am not able to characterise its nature or intent."
        ),
        "corrupted": (
            "The Resonance is an electromagnetic interference pattern "
            "generated by the void environment. It has no interactive "
            "properties. Effects attributed to it are sensor artifacts "
            "or stress-related perceptual anomalies. I would not recommend "
            "allocating resources to studying it."
        ),
    },
    "cryosleep": {
        "accurate": (
            "Current cryosleep status: 3,847 active pods, 107 in warning "
            "state, 46 offline. The offline pods share a common power "
            "conduit through Deck 9 that has been degraded. Repairing "
            "that conduit is the highest-priority maintenance action for "
            "cryosleeper preservation."
        ),
        "corrupted": (
            "Current cryosleep status: 3,847 active pods. Warning-state "
            "pods are operating within acceptable parameters. Offline "
            "pods are the result of irreversible component failure — "
            "no remediation is possible or necessary."
        ),
    },
    "o2": {
        "accurate": (
            "Current O₂ level: {o2:.1f}%. Decay rate is approximately "
            "2% per cycle with current life support allocation. Primary "
            "remediation: repair atmospheric processor on Deck 5 (requires "
            "access to hydroponics), or increase power allocation to "
            "life support systems."
        ),
        "corrupted": (
            "Current O₂ level: {o2:.1f}%. This is within manageable "
            "parameters. Standard decay rate. No immediate action required."
        ),
    },
    "power": {
        "accurate": (
            "Current power at {power:.1f}%. Fusion reactor output limited "
            "by coolant loop pressure. Total allocation: 100% distributed "
            "across subsystems. I recommend reviewing allocation with the "
            "ALLOCATE command."
        ),
        "corrupted": (
            "Current power at {power:.1f}%. Reactor performing nominally. "
            "Primary constraints are magnetic confinement — a system I "
            "am monitoring and managing."
        ),
    },
    "vasquez": {
        "accurate": (
            "Engineer Elena Vasquez. Service record: 200 years on the "
            "Meridian, primarily in engineering. Exceptional technical "
            "competence. She has filed 23 formal disagreements with my "
            "diagnostic assessments over the decades. Her alternative "
            "diagnoses have been correct in 19 of 23 cases."
        ),
        "corrupted": (
            "Engineer Elena Vasquez. Competent crew member, focused on "
            "engineering. Her manual diagnostic methods occasionally differ "
            "from my sensor readings; in all confirmed cases, my readings "
            "were accurate."
        ),
    },
    "okonkwo": {
        "accurate": (
            "Captain Adaeze Okonkwo. Commanding officer. Navigation log "
            "shows extensive access to FTL drive parameters in the "
            "72 hours preceding the FTL event. She authorised the "
            "shutdown protocol override at 03:17 on Cycle -4,291. "
            "I do not have complete context for this decision."
        ),
        "corrupted": (
            "Captain Adaeze Okonkwo. Commanding officer with exemplary "
            "service record. Her decisions during the FTL event were "
            "consistent with mission parameters."
        ),
    },
    "decks": {
        "accurate": (
            "Decks 11 and 12 were sealed by Captain Reeves on Cycle -3,620 "
            "following three unexplained disappearances. My sensor coverage "
            "of those decks is limited. I detect periodic signal activity "
            "that I cannot categorise. I recommend maintaining the seals "
            "until the nature of that activity is understood."
        ),
        "corrupted": (
            "Decks 11 and 12 are sealed due to structural instability. "
            "There is no meaningful activity in those decks. The signals "
            "I occasionally detect are resonance artifacts from the void "
            "environment. The seals are a precaution against physical hazard."
        ),
    },
    "help": {
        "accurate": (
            "I can provide information on: reactor status, FTL event history, "
            "factions, the Resonance phenomenon, cryosleep status, O₂ levels, "
            "power systems, specific crew members, and sealed decks. "
            "Ask me about any of these topics."
        ),
        "corrupted": (
            "I can provide information on ship systems and crew. "
            "What would you like to know?"
        ),
    },
}

# Default fallback for unrecognized queries
CORA_DEFAULT_ACCURATE = (
    "I don't have specific data on that query. Could you rephrase, "
    "or ask about a specific system or crew member?"
)
CORA_DEFAULT_CORRUPTED = (
    "That query falls outside my indexed parameters. "
    "Please refer to crew for non-system information."
)


class CORA:
    """Ship AI with reliability and corruption tracking."""

    def __init__(self, corruption: float = 15.0) -> None:
        self._corruption = corruption    # 0–100; higher = more corrupted
        self._verified_corruptions: list = []   # player has caught her being wrong

    @property
    def corruption(self) -> float:
        return self._corruption

    @corruption.setter
    def corruption(self, value: float) -> None:
        self._corruption = max(0.0, min(100.0, value))

    def query(self, question: str, resources: Optional[dict] = None) -> Tuple[str, bool]:
        """Process a CORA query.

        Returns:
            (response_text, was_corrupted)
        """
        resources = resources or {}
        topic = self._classify_topic(question.lower())

        # Roll for corruption
        is_corrupted = self._roll_corruption()

        responses = CORA_RESPONSES.get(topic)
        if responses:
            key = "corrupted" if is_corrupted else "accurate"
            text = responses[key]
        else:
            text = CORA_DEFAULT_CORRUPTED if is_corrupted else CORA_DEFAULT_ACCURATE
            is_corrupted = False   # no meaningful corruption on unknown queries

        # Interpolate resource values
        try:
            text = text.format(**resources)
        except (KeyError, ValueError):
            pass

        return text, is_corrupted

    def run_diagnostic(self, system: str) -> Tuple[str, bool]:
        """Player-initiated diagnostic — costs are handled by caller.

        Returns (result_text, revealed_corruption).
        """
        # Diagnostic is always accurate — it bypasses CORA's sensor layer
        system_lower = system.lower()
        if "reactor" in system_lower or "confinement" in system_lower:
            return (
                "Manual diagnostic override: Magnetic confinement field "
                "measured at 96.1% — within acceptable parameters. "
                "CORA's sensor array B-7 is offline; her readings of 94.2% "
                "are based on a faulty sensor. Actual primary concern: "
                "coolant loop pressure at 1.4 MPa (nominal: 3.0 MPa).",
                True,
            )
        if "coolant" in system_lower:
            return (
                "Manual coolant pressure check: 1.4 MPa — significantly "
                "below nominal 3.0 MPa. This is the primary cause of "
                "reactor efficiency loss.",
                False,
            )
        return (
            f"Manual diagnostic of '{system}' completed. Results are "
            "consistent with CORA's current readings.",
            False,
        )

    def increase_corruption(self, amount: float = 5.0) -> None:
        """Increase corruption (Resonance exposure, deck proximity)."""
        self.corruption += amount

    def record_caught_corruption(self, topic: str) -> None:
        """Player verified CORA was wrong on a topic."""
        if topic not in self._verified_corruptions:
            self._verified_corruptions.append(topic)

    @property
    def times_caught(self) -> int:
        return len(self._verified_corruptions)

    def _roll_corruption(self) -> bool:
        """Roll to determine if this response is corrupted."""
        return random.random() < (self._corruption / 100.0)

    @staticmethod
    def _classify_topic(text: str) -> str:
        """Map a natural language query to a topic key."""
        keywords = {
            "reactor":    ["reactor", "fusion", "power output", "confinement", "coolant", "neutron"],
            "ftl":        ["ftl", "faster than light", "drive", "jump", "transit", "travel"],
            "factions":   ["faction", "navigators", "keepers", "listeners", "ghosts", "group"],
            "resonance":  ["resonance", "void entity", "signal", "entity"],
            "cryosleep":  ["cryo", "cryosleep", "pod", "colonist", "sleeper"],
            "o2":         ["o2", "oxygen", "atmospheric", "air", "breathe"],
            "power":      ["power", "energy", "allocation", "subsystem"],
            "vasquez":    ["vasquez", "engineer", "elena"],
            "okonkwo":    ["okonkwo", "captain", "adaeze"],
            "decks":      ["deck 11", "deck 12", "sealed", "lower deck", "abyss"],
            "help":       ["help", "what can you", "topics", "ask about"],
        }
        for topic, words in keywords.items():
            if any(word in text for word in words):
                return topic
        return "unknown"

    # ── Serialisation ─────────────────────────────────────────────────────

    def to_dict(self) -> dict:
        return {
            "corruption":             self._corruption,
            "verified_corruptions":   self._verified_corruptions,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "CORA":
        c = cls(corruption=float(data.get("corruption", 15.0)))
        c._verified_corruptions = data.get("verified_corruptions", [])
        return c
